#!/usr/bin/env bash

ntuplesGeneralLocation="/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/wtabb/DrellYan_13TeV_2016/v2p6/"
skimTag="/skims_MuMu"

sampleLocation=(
	DYLL_M10to50/DYLL_M10to50/EE/v1
	DYLL_M10to50/DYLL_M10to50/MuMu/v1
	DYLL_M10to50/DYLL_M10to50/TauTau/v1
	DYLL_M10to50/DYLL_M10to50/EE/v2
	DYLL_M10to50/DYLL_M10to50/MuMu/v2
	DYLL_M10to50/DYLL_M10to50/TauTau/v2
	DYLL_M10to50/DYLL_M10to50/EE/ext1v1
	DYLL_M10to50/DYLL_M10to50/MuMu/ext1v1
	DYLL_M10to50/DYLL_M10to50/TauTau/ext1v1
	DYLL_M50toInf/DYLL_M50toInf_truncated_M50To100/EE/base
	DYLL_M50toInf/DYLL_M50toInf_truncated_M50To100/MuMu/base
	DYLL_M50toInf/DYLL_M50toInf_truncated_M50To100/TauTau/base
	DYLL_M100to200/DYLL_M100to200/EE
	DYLL_M100to200/DYLL_M100to200/MuMu
	DYLL_M100to200/DYLL_M100to200/TauTau
	DYLL_M200to400/DYLL_M200to400/EE
	DYLL_M200to400/DYLL_M200to400/MuMu
	DYLL_M200to400/DYLL_M200to400/TauTau
	DYLL_M400to500/DYLL_M400to500/EE
	DYLL_M400to500/DYLL_M400to500/MuMu
	DYLL_M400to500/DYLL_M400to500/TauTau
	DYLL_M500to700/DYLL_M500to700/EE
	DYLL_M500to700/DYLL_M500to700/MuMu
	DYLL_M500to700/DYLL_M500to700/TauTau
	DYLL_M700to800/DYLL_M700to800/EE
	DYLL_M700to800/DYLL_M700to800/MuMu
	DYLL_M700to800/DYLL_M700to800/TauTau
	DYLL_M800to1000/DYLL_M800to1000/EE
	DYLL_M800to1000/DYLL_M800to1000/MuMu
	DYLL_M800to1000/DYLL_M800to1000/TauTau
	DYLL_M1000to1500/DYLL_M1000to1500/EE
	DYLL_M1000to1500/DYLL_M1000to1500/MuMu
	DYLL_M1000to1500/DYLL_M1000to1500/TauTau
	DYLL_M1500to2000/DYLL_M1500to2000/EE
	DYLL_M1500to2000/DYLL_M1500to2000/MuMu
	DYLL_M1500to2000/DYLL_M1500to2000/TauTau
	DYLL_M2000to3000/DYLL_M2000to3000/EE
	DYLL_M2000to3000/DYLL_M2000to3000/MuMu
	DYLL_M2000to3000/DYLL_M2000to3000/TauTau
	WW
	WZ
	ZZ
	ZToEE_M50to120
	ZToEE_M120to200
	ZToEE_M200to400
	ZToEE_M400to800
	ZToEE_M800to1400
	ZToEE_M1400to2300
	ZToEE_M2300to3500
	ZToEE_M3500to4500
	ZToEE_M4500to6000
	ZToEE_M6000toInf
	ttbar
	ttbarBackup
	ttbar_truncated_M0To700
	ttbarBackup_truncated_M0To700
	ttbar_M700to1000
	ttbar_M1000toInf
	ST_tW
	ST_tbarW
	WJetsToLNu_amcatnlo
	WJetsToLNu_amcatnlo_ext
	WJetsToLNu_amcatnlo_ext2v5
	SingleMuon_Run2016B
	SingleMuon_Run2016C
	SingleMuon_Run2016D
	SingleMuon_Run2016E
	SingleMuon_Run2016F
	SingleMuon_Run2016G
	SingleMuon_Run2016Hver2
	SingleMuon_Run2016Hver3
	crab_DoubleEG_RunB
	crab_DoubleEG_RunC
	crab_DoubleEG_RunD
	crab_DoubleEG_RunE
	crab_DoubleEG_RunF
	crab_DoubleEG_RunG
	crab_DoubleEG_RunHver2
	crab_DoubleEG_RunHver3
	QCDMuEnriched_Pt15to20
        QCDMuEnriched_Pt20to30
        QCDMuEnriched_Pt30to50
        QCDMuEnriched_Pt50to80
        QCDMuEnriched_Pt80to120
        QCDMuEnriched_Pt80to120_ext1
        QCDMuEnriched_Pt120to170
        QCDMuEnriched_Pt120to170_backup
        QCDMuEnriched_Pt170to300
        QCDMuEnriched_Pt170to300_backup
        QCDMuEnriched_Pt170to300_ext1
        QCDMuEnriched_Pt300to470
        QCDMuEnriched_Pt300to470_ext1
        QCDMuEnriched_Pt300to470_ext2
        QCDMuEnriched_Pt470to600
        QCDMuEnriched_Pt600to800
        QCDMuEnriched_Pt600to800_backup
        QCDMuEnriched_Pt600to800_ext1
        QCDMuEnriched_Pt800to1000
        QCDMuEnriched_Pt800to1000_ext1
        QCDMuEnriched_Pt800to1000_ext2
        QCDMuEnriched_Pt1000toInf
        QCDMuEnriched_Pt1000toInf_ext1
)


for index in ${!sampleLocation[*]}; do 
	if [ -d ${ntuplesGeneralLocation}${sampleLocation[$index]}${skimTag} ]
	then
		echo ${sampleLocation[$index]}
		cd ${ntuplesGeneralLocation}${sampleLocation[$index]}${skimTag}
		ls -l *.root | wc -l
		cd ../
		ls -l *.root | wc -l
	else
		echo ${ntuplesGeneralLocation}${sampleLocation[$index]}${skimTag}" does not exist!"
	fi
done
