#!/bin/bash

# If there are just a few files which were not properly skimmed
# I can use this script to submit those individual files locally
# rather than submitting to Condor again

path=/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/wtabb/DrellYan_13TeV_2016/v2p6
sampleName=(
       ttbar
       ttbar
       ttbarBackup
       ttbarBackup
       ttbarBackup
)

skimTag=_skims0001
shortName=(
	ntuple_skim_19.root
	ntuple_skim_546.root
	ntuple_skim_381.root
	ntuple_skim_831.root
	ntuple_skim_864.root
) 
preserveCount = true;

for index in ${!sampleName[*]}; do
root -l << EOF
.L kimGoodEvents.C
TString rPath = "${path}"
TString rSampleName = "${sampleName[index]}${shortName[index]}"
TString rSkimTag = "${skimTag}"
bool rPreserveCount = ${preserveCount}
filterOnGenMass(rPath,rSampleName,rSkimTag,rPreserveCount)
EOF
done
