#!/usr/bin/env bash

ntuplesGeneralLocation="/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/wtabb/DrellYan_13TeV_2016/v2p6/"

sampleLocation1=(
    DYLL_M10to50/v1
    DYLL_M10to50/v2
    DYLL_M10to50/ext1v1
    DYLL_M50toInf_truncated_M50To100/base
    DYLL_M100to200
    DYLL_M200to400
    DYLL_M400to500
    DYLL_M500to700
    DYLL_M700to800
    DYLL_M800to1000
    DYLL_M1000to1500
    DYLL_M1500to2000
    DYLL_M2000to3000
)
sampleLocation2=(
    DYLL_M10to50/DYLL_M10to50/EE/v1
    DYLL_M10to50/DYLL_M10to50/EE/v2
    DYLL_M10to50/DYLL_M10to50/EE/ext1v1
    DYLL_M50toInf/DYLL_M50toInf_truncated_M50To100/EE/base
    DYLL_M100to200/DYLL_M100to200/EE
    DYLL_M200to400/DYLL_M200to400/EE
    DYLL_M400to500/DYLL_M400to500/EE
    DYLL_M500to700/DYLL_M500to700/EE
    DYLL_M700to800/DYLL_M700to800/EE
    DYLL_M800to1000/DYLL_M800to1000/EE
    DYLL_M1000to1500/DYLL_M1000to1500/EE
    DYLL_M1500to2000/DYLL_M1500to2000/EE
    DYLL_M2000to3000/DYLL_M2000to3000/EE
)


for index in ${!sampleLocation2[*]}; do 
	echo "Comparing: "
	echo ${ntuplesGeneralLocation}${sampleLocation1[$index]}
	echo "And:"
	echo ${ntuplesGeneralLocation}${sampleLocation2[$index]}
	cd ${ntuplesGeneralLocation}${sampleLocation1[$index]}
	ls -l *.root | wc -l
	cd ${ntuplesGeneralLocation}${sampleLocation2[$index]}
	ls -l *.root | wc -l
done
