#!/bin/bash

# This will recursively delete all samples split by lepton type 
# This is useful if a mistake was made in creating them and they need to be remade
# Be careful that the directories listed here are the right ones before running this code
# I am leaving the line to remove the files commented out so that this script will not 
# accidentally be run
# Remove the comment on line 28 to use this

base_directory=/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/wtabb/DrellYan_13TeV_2016/v2p6/

file_list=(
	DYLL_M10to50/DYLL_M10to50
	DYLL_M50toInf/DYLL_M50toInf_truncated_M50To100
	DYLL_M100to200/DYLL_M100to200
	DYLL_M200to400/DYLL_M200to400
	DYLL_M400to500/DYLL_M400to500
	DYLL_M500to700/DYLL_M500to700
	DYLL_M700to800/DYLL_M700to800
	DYLL_M800to1000/DYLL_M800to1000
	DYLL_M1000to1500/DYLL_M1000to1500
	DYLL_M1500to2000/DYLL_M1500to2000
	DYLL_M2000to3000/DYLL_M2000to3000
)

for index in ${!file_list[*]}; do
	echo "Removing directory: ${file_list[$index]}"
#	rm -r ${base_directory}${file_list[$index]}
done
